"""Robust PPO v2 browser contract on actual hosted/generated bytes."""
import argparse,json,os
from pathlib import Path
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1]
parser=argparse.ArgumentParser();parser.add_argument('--base-url');parser.add_argument('--output',type=Path,default=ROOT/'evidence/robust-v2-browser');args=parser.parse_args();args.output.mkdir(parents=True,exist_ok=True)
report={'checks':[],'errors':[]}
def check(name,condition,detail=None):
    if not condition: raise AssertionError((name,detail))
    report['checks'].append({'name':name,'passed':True,'detail':detail});print('PASS',name,flush=True)
with sync_playwright() as pw:
    channel=os.environ.get('BROWSER_CHANNEL')
    exe=None if channel else (os.environ.get('CHROMIUM_PATH') or ('/usr/bin/chromium' if Path('/usr/bin/chromium').exists() else None))
    browser=pw.chromium.launch(channel=channel,executable_path=exe,headless=True,args=['--no-sandbox'])
    page=browser.new_page(viewport={'width':1600,'height':1050});page.set_default_timeout(30000);page.on('pageerror',lambda e:report['errors'].append(str(e)))
    try:
        if args.base_url: page.goto(args.base_url.rstrip('/')+'/',wait_until='load',timeout=90000)
        else: page.set_content((ROOT/'index.html').read_text(),wait_until='load')
        page.wait_for_function('window.PPOStep && PPOStep.status().ready')
        page.click('[data-chapter="5"]')
        check('Robust method does not add a second animated CartPole',page.locator('#world').count()==1)
        check('Robust panel exists as progressive disclosure',page.locator('#robustV2').count()==1)
        page.locator('#robustV2 summary').click()
        page.wait_for_function('window.RobustUI && RobustUI.status().ready')
        check('Method states continuous action, history and asymmetric critic',all(x in page.locator('#robustMethod').inner_text().lower() for x in ['continuous','history','critic']))
        s0=page.evaluate('RobustUI.status()')
        check('Fresh robust learner is independent and starts at I.0',s0['latestIteration']==0 and s0['boundary']==.1)
        page.click('#robustOneIteration')
        page.wait_for_function('RobustUI.status().latestIteration===1 && !RobustUI.status().busy',timeout=90000)
        s1=page.evaluate('RobustUI.status()')
        check('One robust iteration collects 2048 transitions',s1['transitions']==2048,s1)
        check('One robust iteration makes 64 Adam updates per network',s1['actorAdam']==64 and s1['criticAdam']==64,s1)
        check('Curriculum does not expand on iteration count alone',s1['boundary']==.1)
        identity=page.evaluate('JSON.stringify(RobustUI.status())')
        page.select_option('#language','ko');page.select_option('#language','en')
        after=page.evaluate('RobustUI.status()')
        check('Language switch preserves robust training state',after['latestIteration']==1 and after['boundary']==.1 and after['actorAdam']==64)
        page.evaluate('RobustUI.evaluateEnvelope({ratios:[0,.5,1,1.25],durations:[.05,.2],trials:2,seed:4400})')
        page.wait_for_function('RobustUI.status().envelope && RobustUI.status().envelope.length===8',timeout=90000)
        env=page.evaluate('RobustUI.status().envelope')
        check('Envelope produces every requested force-duration cell',len(env)==8)
        check('Envelope separates stress OOD cells above authority one',sum(1 for x in env if x['stressOOD'])==2)
        check('Envelope reports model-invalid outcomes explicitly',all('modelInvalid' in x for x in env))
        check('Envelope renders without another simulation canvas',page.locator('#robustEnvelopeTable canvas').count()==0 and page.locator('#world').count()==1)
        page.screenshot(path=str(args.output/'robust-v2.png'),full_page=True)
        check('No browser JavaScript errors',not report['errors'],report['errors'])
        report['passed']=True
    except Exception as exc:
        report['passed']=False;report['error']=str(exc);page.screenshot(path=str(args.output/'failure.png'),full_page=True);raise
    finally:
        (args.output/'report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2));browser.close()
