'use strict';
// Fixed-budget, multi-seed qualification experiment. This script deliberately
// does not pick the best checkpoint and does not fail CI merely because the
// robustness acceptance gate fails; the full result remains evidence.
const fs=require('node:fs'),path=require('node:path');
const ROOT=path.resolve(__dirname,'..'),E=require('../src/core'),P=require('../src/plant'),R=require('../src/robust_v2');
const seeds=(process.env.ROBUST_SEEDS||'123,456,789').split(',').map(Number),budget=Number(process.env.ROBUST_ITERATIONS||120),trials=Number(process.env.ROBUST_TRIALS||12);
const ratios=(process.env.ROBUST_RATIOS||'0,0.1,0.2,0.35,0.5,0.65,0.8,1,1.25').split(',').map(Number),durations=(process.env.ROBUST_DURATIONS||'0.1,0.2').split(',').map(Number);
if(!seeds.length||seeds.some(x=>!Number.isInteger(x))||!Number.isInteger(budget)||budget<1||!Number.isInteger(trials)||trials<1)throw Error('Invalid experiment configuration.');

function legacyRollout(snapshot,{ratio=0,duration=.1,seed=810000,goal=.8,sign=1,mixed=false}={}){
 const actor=E.MLP.from(snapshot.actor),env=new E.CartPole(new E.RNG(seed),{spec:snapshot.plant||P.DEFAULT_SPEC,profile:mixed?'mixed':'nominal',level:mixed?Math.min(1,ratio||.5):0,seed:(seed+700001)>>>0});env.reset(goal);if(mixed)env.params.pushAmp=0;
 const tipAmp=R.tipForceForAuthority(env.spec,env.params,ratio),start=1,tail=[];let maxAngle=0,maxError=0,sat=0,steps=0,recoveryTime=null,dwell=0;
 while(!env.done){const time=env.steps*E.DT,tip=time>=start&&time<start+duration?sign*tipAmp:0,ac=E.policy(actor,env.obs(),true),out=env.step(ac.a,0,tip);steps++;maxAngle=Math.max(maxAngle,Math.abs(env.s[2]*180/Math.PI));maxError=Math.max(maxError,Math.abs(env.s[0]-goal));if(out.drive.saturated)sat++;if(env.steps>=350)tail.push(Math.abs(env.s[0]-goal));if(time>=start+duration){const safe=Math.abs(env.s[2])<3*Math.PI/180&&Math.abs(env.s[3])<.5&&Math.abs(env.s[0]-goal)<.25&&Math.abs(env.s[1])<.4;dwell=safe?dwell+1:0;if(recoveryTime===null&&dwell>=25)recoveryTime=(env.steps*E.DT)-(start+duration)-.5;}}
 const tailError=env.steps===500&&tail.length?E.avg(tail):null,success=!env.terminated&&env.steps===500&&tailError!==null&&tailError<.25;
 return {success,modelInvalid:!!env.validityLimit,steps:env.steps,tailError,maxAngle,maxError,recoveryTime,saturationFraction:steps?sat/steps:0};
}
function evaluateLegacyEnvelope(snapshot,seedBase){const rows=[];for(const duration of durations)for(const ratio of ratios){let successes=0,modelInvalid=0,maxAngle=0,maxError=0,sat=0,recovery=[];for(let i=0;i<trials;i++){const r=legacyRollout(snapshot,{ratio,duration,seed:seedBase+rows.length*10007+i*193,goal:[.8,-.8,0][i%3],sign:i%2?1:-1});if(r.success)successes++;if(r.modelInvalid)modelInvalid++;maxAngle=Math.max(maxAngle,r.maxAngle);maxError=Math.max(maxError,r.maxError);sat+=r.saturationFraction;if(r.recoveryTime!==null)recovery.push(r.recoveryTime);}rows.push({ratio,duration,trials,successes,modelInvalid,maxAngle,maxError,recoveryTime:recovery.length?E.avg(recovery):null,saturationFraction:sat/trials,stressOOD:ratio>1});}return rows;}
function nominalLegacy(snapshot,seedBase){let success=0,steps=0,invalid=0;for(let i=0;i<trials;i++){const r=legacyRollout(snapshot,{ratio:0,duration:.1,seed:seedBase+i*193,goal:[.8,-.8,0][i%3]});success+=r.success;steps+=r.steps;invalid+=r.modelInvalid;}return {success,trials,meanSteps:steps/trials,modelInvalid:invalid};}
function nominalRobust(snapshot,seedBase){let success=0,steps=0,invalid=0;for(let i=0;i<trials;i++){const r=R.rollout(snapshot,{ratio:0,duration:.1,seed:seedBase+i*193,goal:[.8,-.8,0][i%3]});success+=r.success;steps+=r.steps;invalid+=r.modelInvalid;}return {success,trials,meanSteps:steps/trials,modelInvalid:invalid};}
function mixedScore(snapshot,isRobust,seedBase,ratio=.35){let success=0,invalid=0,steps=0;for(let i=0;i<trials;i++){const opt={ratio,duration:.12,seed:seedBase+i*193,goal:[.8,-.8,0][i%3],sign:i%2?1:-1,mixed:true},r=isRobust?R.rollout(snapshot,opt):legacyRollout(snapshot,opt);success+=r.success;invalid+=r.modelInvalid;steps+=r.steps;}return {success,trials,meanSteps:steps/trials,modelInvalid:invalid,ratio};}
function aggregateEnvelope(runs,key){const map=new Map();for(const run of runs)for(const x of run[key].envelope){const id=`${x.duration}:${x.ratio}`,v=map.get(id)||{duration:x.duration,ratio:x.ratio,trials:0,successes:0,modelInvalid:0,stressOOD:x.stressOOD};v.trials+=x.trials;v.successes+=x.successes;v.modelInvalid+=x.modelInvalid;map.set(id,v);}return [...map.values()].sort((a,b)=>a.duration-b.duration||a.ratio-b.ratio);}
function sumNested(runs,key,subkey,field){return runs.reduce((s,r)=>s+r[key][subkey][field],0);}

const runs=[];
for(const seed of seeds){
 console.log(`seed ${seed}: training legacy ${budget} iterations`);
 const legacy=new E.Trainer(seed,{plant:P.DEFAULT_SPEC,profile:'nominal',plan:'fixed'});for(let i=0;i<budget;i++)legacy.iteration();
 console.log(`seed ${seed}: training robust-v2 ${budget} iterations`);
 const robust=new R.Trainer(seed,{plant:P.DEFAULT_SPEC});for(let i=0;i<budget;i++){robust.iteration();if((i+1)%20===0)console.log(`  robust I.${i+1} boundary=${robust.boundary.value.toFixed(2)} gate=${robust.gateResult?`${robust.gateResult.nominal}/${robust.gateResult.tip}/${robust.gateResult.mixed}`:'-'}`);}
 const legacyPolicy=legacy.snapshot(),robustPolicy=robust.snapshot(),testSeed=5_000_000+seed*1000,legacyNominalEval=legacy.evaluate();
 runs.push({seed,budget,legacy:{nominal:nominalLegacy(legacyPolicy,testSeed),mixed:mixedScore(legacyPolicy,false,testSeed+100000),envelope:evaluateLegacyEnvelope(legacyPolicy,testSeed+200000),train:{nominalMean:legacyNominalEval.mean,nominalPassed:legacyNominalEval.reached}},robust:{nominal:nominalRobust(robustPolicy,testSeed),mixed:mixedScore(robustPolicy,true,testSeed+100000),envelope:R.evaluateEnvelope(robustPolicy,{ratios,durations,trials,seed:testSeed+200000}),train:{boundary:robust.boundary.value,boundaryIndex:robust.boundary.index,gate:robust.gateResult,trainMean:robust.scores.length?E.avg(robust.scores):null}}});
}
const legacyEnvelope=aggregateEnvelope(runs,'legacy'),robustEnvelope=aggregateEnvelope(runs,'robust'),cellPairs=legacyEnvelope.map((l,i)=>({legacy:l,robust:robustEnvelope[i],deltaRate:robustEnvelope[i].successes/robustEnvelope[i].trials-l.successes/l.trials})),inRange=cellPairs.filter(x=>x.legacy.ratio>0&&x.legacy.ratio<=.8),bestInRange=inRange.slice().sort((a,b)=>b.deltaRate-a.deltaRate)[0];
const nominalLegacyTotal=sumNested(runs,'legacy','nominal','success'),nominalRobustTotal=sumNested(runs,'robust','nominal','success'),totalNominal=seeds.length*trials,mixedLegacyTotal=sumNested(runs,'legacy','mixed','success'),mixedRobustTotal=sumNested(runs,'robust','mixed','success'),totalMixed=seeds.length*trials;
const acceptance={noMaterialNominalCollapse:nominalRobustTotal>=nominalLegacyTotal-Math.ceil(.1*totalNominal),improvesInRange:!!bestInRange&&bestInRange.deltaRate>0,improvesMixed:mixedRobustTotal>mixedLegacyTotal};acceptance.accepted=acceptance.noMaterialNominalCollapse&&(acceptance.improvesInRange||acceptance.improvesMixed);
const report={schema:'cartpole-robust-v2-experiment/v1',generatedAt:new Date().toISOString(),method:{seeds,budgetIterations:budget,transitionsPerIteration:2048,trialsPerCondition:trials,ratios,durations,checkpointSelection:'final fixed-budget checkpoint; no best-checkpoint selection',testSeeds:'disjoint from training/gate RNG',stressOOD:'authority ratio > 1.0 excluded from acceptance'},runs,aggregate:{nominal:{legacy:{successes:nominalLegacyTotal,trials:totalNominal},robust:{successes:nominalRobustTotal,trials:totalNominal}},mixed35:{legacy:{successes:mixedLegacyTotal,trials:totalMixed},robust:{successes:mixedRobustTotal,trials:totalMixed}},legacyEnvelope,robustEnvelope,bestInRange},acceptance};
fs.mkdirSync(path.join(ROOT,'evidence'),{recursive:true});fs.writeFileSync(path.join(ROOT,'evidence','robust_v2_experiment.json'),JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify({acceptance,nominal:report.aggregate.nominal,mixed35:report.aggregate.mixed35,bestInRange},null,2));
